# Based on https://github.com/MTrab/landroid_cloud/blob/37c786c8d61ab235fd23f46cbc475295ac43c887/.github/workflows/release.yml

name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  COMPONENT_DIR: copenhagen_trackers

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Update manifest.json version to ${{ github.event.release.tag_name }}
        run: |
          python3 ${{ github.workspace }}/.github/scripts/update_hacs_manifest.py --version ${{ github.event.release.tag_name }} --path /custom_components/copenhagen_trackers/
      - name: Commit manifest update
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./custom_components/copenhagen_trackers/manifest.json
          git commit -m "Updated manifest.json"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Lerbaek/hass-copenhagen-trackers.git HEAD:master
      - name: Create zip
        run: |
          cd custom_components/copenhagen_trackers
          zip copenhagen_trackers.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/copenhagen_trackers/copenhagen_trackers.zip
          asset_name: copenhagen_trackers.zip
          tag: ${{ github.ref }}
          overwrite: true